### ISSUE TITLE
[BUG] Alien killing the player with a barrel 

### ISSUE THREAD

**Issue by TheoDct** [algosup/2022-2023-project-4-game-design-Team-7#1]
In the first level, the player can be killed if he comes out of an alien in the path of the barrels, even if he is not hit directly by a barrel, he can still be killed if the barrel hits a previously controlled alien. 

- Expected behaviour:
The barrel was supposed to kill the alien not the player

- Steps to reproduce:
1. Take over an alien 
2. Get out of it on the path of the barrels 
3. Wait till a barrel hits the alien 

@ivan-molnar @Louis-de-Lavenne-de-Choulot

**Comment by maxbernard3** [comment]
Fixed.
It was an issue with the barrel resetting the game on hitting any any alien without checking if it was player controlled.
now uncontrolled alien get destroyed when hit.
